### ISSUE TITLE
Korrespondenz E-Mail

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#10]
- [x] F04-08 Das System nutzt eine entsprechende Vorlage für Rechnungen/Mahnungen automatisch. #30 
- [x] F04-16 Mailchimp bounces integrieren, Personen markieren #31
- [x] F04-17 Personen Filter via tags, Emails anpassen #32
- [x] F04-18 Korrespondenz auf Personen und Firmen sichtbar, Kommunikationshistorie #33
