### ISSUE TITLE
Kampagnen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#12]
Neues Modul Kampagen

- Attribute festlegen, Kampangnen Rückläufe, neue Attribute zur Laufzeit?
- Sonst ähnlich Event (Vorschläge machen Selektionsliste, Einladungen, Reminder, Vorlagen)

**Aus dem Workshop vom 10.09.2020**
Funktionalitäten, welche bislang mit Kampagnen gelöst wurden, werden auf die Module Rechnungen und Filter verteilt.

- [x] Selektionen
- [x] Rechnungen
    - [x] Mitgliederbeiträge
    - [x] Rechnungen an gewisse Personenkreise
    - [x] Wie viel ist noch offen, wie viel ist bereits bezahlt, anzahl Kontakte
    - [x] Gruppen von Rechnungen
    - [x] Exkluden von Personen mit gewissen Tags
