### ISSUE TITLE
F04-19 SMS an mehrere Personen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#34]
- Inputfeld max 160 zeichen begrenzen
- Geschickte SMS auf dem Abo anzeigen
- ~~Im Abo kann zusätzlich an die Empfänger ein SMS geschickt werden.~~ #38
- Ein SMS wird an alle Nummer mit dem Typ "mobile" geschickt.
- Nur mit der Rolle "Sekretariat" kann ein SMS geschickt werden.
- ~~Wie Mails, werden SMS Kommunikation auch im "history" abgelget~~ Wird mit #37 umgesetzt
- SMS Provider: https://www.aspsms.com/de/documentation/
- Einstellungen Provider auf Group Setttings

- [ ] SMS kann nur gesendet werden falls Provider Settings vorhanden (senden button disablen)
- [ ] Im Form Anzeigen an wie viele Empfänger das die SMS gesendet wird #101 
- [ ] Im Form Anzeigen wieviele Empfänger keine Mobil Nr hinterlegt haben #101 
- [ ] Anzahl Zeichen im Form anzeigen #102

https://aspsms.ch (ca 6-10 Rp pro SMS, keine Grundgebühr)

**Comment by ninfaj** [comment]
Evtl. wäre dies eine gute Möglichkeit mit den Aktionen etwas aufzuräumen?
Über die Aktion "Kommunikation" (oder "Versenden", "Kontaktaufnahme", ...) könnte man die hinterlegte E-Mail Adresse kopieren, SMS verschicken und Briefe vorbereiten (#8)
![image](https://user-images.githubusercontent.com/157533/95300707-ce4db500-087f-11eb-9b78-f50906a9d677.png)

**Comment by ninfaj** [comment]
zusätzlicher Input:
Beim Formular zum Verschicken von SMS wäre es sicher sinnvoll eine Meldung anzuzeigen, falls es Personen im Abo hat, für welche keine Mobile Nummer erfasst ist.
![image](https://user-images.githubusercontent.com/157533/95301973-9a738f00-0881-11eb-8def-4d266e8ab405.png)

**Comment by psunix** [comment]
![htbt-msgs](https://user-images.githubusercontent.com/655627/100749616-34206e00-33e5-11eb-9ecd-34c5c779432d.jpeg)

**Comment by carlobeltrame** [comment]
Beim Versand von SMS sollten wir noch testen ob Umlaute korrekt abgesendet werden. Wenn Emoji nicht unterstützt werden könnte ich das noch gut verstehen, aber ich habe es bei decidim bisher nicht geschafft, Umlaute zu senden.
